declare const process:{exitCode?:number};
import { EARTH } from '../core/constants.js';
import { cross3,dot3,normalize3,type Vec3 } from '../core/math.js';
import { buildCubedSphere,type CubedSphereGrid } from '../grid/cubedSphere.js';
import { applyNonorthogonalHodge,buildNonorthogonalHodgeStencil,hodgeSymmetryDefect } from '../grid/nonorthogonalHodge.js';
import { buildModifiedCubedSphere } from '../grid/modifiedCubedSphere.js';

const GLX=[-0.9602898564975363,-0.7966664774136267,-0.5255324099163290,-0.1834346424956498,0.1834346424956498,0.5255324099163290,0.7966664774136267,0.9602898564975363];
const GLW=[0.1012285362903763,0.2223810344533745,0.3137066458778873,0.3626837833783620,0.3626837833783620,0.3137066458778873,0.2223810344533745,0.1012285362903763];
const AXIS=normalize3([.31,-.47,.826] as Vec3),ROT=11,GRAD:Vec3=[9,-6,7];
function center(h:CubedSphereGrid,c:number):Vec3{return[h.cellCenters[c*3]!,h.cellCenters[c*3+1]!,h.cellCenters[c*3+2]!];}
function tangentToward(a:Vec3,b:Vec3):Vec3{const ab=dot3(a,b),d:Vec3=[b[0]-ab*a[0],b[1]-ab*a[1],b[2]-ab*a[2]];return normalize3(d);}
function basis(r:Vec3):{east:Vec3;north:Vec3}{const q=Math.hypot(r[0],r[1]),east:Vec3=q>1e-14?[-r[1]/q,r[0]/q,0]:[0,1,0];return{east,north:normalize3(cross3(r,east))};}
function wind(r:Vec3):Vec3{const gd=dot3(GRAD,r),rot=cross3(AXIS,r);return[GRAD[0]-gd*r[0]+ROT*rot[0],GRAD[1]-gd*r[1]+ROT*rot[1],GRAD[2]-gd*r[2]+ROT*rot[2]];}
function coriolis(r:Vec3,u:Vec3):Vec3{const rxu=cross3(r,u),f=2*EARTH.omega*r[2];return[-f*rxu[0],-f*rxu[1],-f*rxu[2]];}
function arcSetup(a:Vec3,b:Vec3):{delta:number;t0:Vec3}{const ab=Math.max(-1,Math.min(1,dot3(a,b))),delta=Math.acos(ab),sd=Math.sin(delta);if(!(delta>0)||Math.abs(sd)<1e-14)throw new Error('degenerate geodesic arc');return{delta,t0:[(b[0]-ab*a[0])/sd,(b[1]-ab*a[1])/sd,(b[2]-ab*a[2])/sd]};}
function integrateArc(a:Vec3,b:Vec3,fn:(r:Vec3,t:Vec3)=>number):number{const {delta,t0}=arcSetup(a,b),half=.5*delta,mid=half;let sum=0;for(let i=0;i<GLX.length;i++){const th=mid+half*GLX[i]!,co=Math.cos(th),si=Math.sin(th),r:Vec3=[co*a[0]+si*t0[0],co*a[1]+si*t0[1],co*a[2]+si*t0[2]],t:Vec3=[-si*a[0]+co*t0[0],-si*a[1]+co*t0[1],-si*a[2]+co*t0[2]];sum+=GLW[i]!*fn(r,t);}return EARTH.radius*half*sum;}
function analyticV(h:CubedSphereGrid):Float64Array{const V=new Float64Array(h.edgeCount);for(let e=0;e<h.edgeCount;e++){const ge=h.edges[e]!,l=center(h,ge.leftCell),r=center(h,ge.rightCell);V[e]=integrateArc(l,r,(x,t)=>dot3(wind(x),t));}return V;}
function analyticDV(h:CubedSphereGrid):Float64Array{const A=new Float64Array(h.edgeCount);for(let e=0;e<h.edgeCount;e++){const ge=h.edges[e]!,l=center(h,ge.leftCell),r=center(h,ge.rightCell);A[e]=integrateArc(l,r,(x,t)=>dot3(coriolis(x,wind(x)),t));}return A;}
function exactFaceU(h:CubedSphereGrid):Float64Array{const U=new Float64Array(h.edgeCount);for(let e=0;e<h.edgeCount;e++){const ge=h.edges[e]!;U[e]=integrateArc(ge.p0,ge.p1,x=>dot3(wind(x),ge.normal));}return U;}

interface DualReconstruction{east:Float64Array;north:Float64Array;weights:Float64Array;dualLength:Float64Array;}
function buildDualReconstruction(h:CubedSphereGrid):DualReconstruction{const east=new Float64Array(h.cellCount*3),north=new Float64Array(h.cellCount*3),weights=new Float64Array(h.cellCount*8),dualLength=new Float64Array(h.edgeCount);for(let e=0;e<h.edgeCount;e++){const ge=h.edges[e]!,l=center(h,ge.leftCell),r=center(h,ge.rightCell);dualLength[e]=Math.acos(Math.max(-1,Math.min(1,dot3(l,r))))*EARTH.radius;}for(let c=0;c<h.cellCount;c++){const cc=center(h,c),b=basis(cc);east.set(b.east,c*3);north.set(b.north,c*3);let aa=0,ab=0,bb=0;const comps:Array<[number,number]>=[];for(let s=0;s<4;s++){const eid=h.cellEdges[c*4+s]!,ge=h.edges[eid]!,nb=ge.leftCell===c?ge.rightCell:ge.leftCell,dir=tangentToward(cc,center(h,nb)),a=dot3(dir,b.east),q=dot3(dir,b.north);comps.push([a,q]);aa+=a*a;ab+=a*q;bb+=q*q;}const det=aa*bb-ab*ab;if(Math.abs(det)<1e-14)throw new Error(`singular dual reconstruction at cell ${c}`);const i00=bb/det,i01=-ab/det,i11=aa/det;for(let s=0;s<4;s++){const [a,q]=comps[s]!;weights[(c*4+s)*2]=i00*a+i01*q;weights[(c*4+s)*2+1]=i01*a+i11*q;}}return{east,north,weights,dualLength};}
function reconstruct(h:CubedSphereGrid,g:DualReconstruction,V:ArrayLike<number>):Float64Array{const out=new Float64Array(h.cellCount*3);for(let c=0;c<h.cellCount;c++){let ue=0,vn=0;for(let s=0;s<4;s++){const eid=h.cellEdges[c*4+s]!,ge=h.edges[eid]!,sign=ge.leftCell===c?1:-1,q=sign*V[eid]!/g.dualLength[eid]!;ue+=g.weights[(c*4+s)*2]!*q;vn+=g.weights[(c*4+s)*2+1]!*q;}const o=c*3;out[o]=ue*g.east[o]!+vn*g.north[o]!;out[o+1]=ue*g.east[o+1]!+vn*g.north[o+1]!;out[o+2]=ue*g.east[o+2]!+vn*g.north[o+2]!;}return out;}

function planetaryMassTorque(h:CubedSphereGrid,U:ArrayLike<number>):number{let torque=0;for(let c=0;c<h.cellCount;c++){let flux=0;for(let s=0;s<4;s++)flux+=h.cellEdgeSigns[c*4+s]!*U[h.cellEdges[c*4+s]!]!;const r=center(h,c),cos2=Math.max(0,1-r[2]*r[2]),specific=EARTH.omega*EARTH.radius*EARTH.radius*cos2;/* rho=1; rho_t*A = -outward volume flux */torque+=-flux*specific;}return torque;}
function relativeCoriolisTorque(h:CubedSphereGrid,g:DualReconstruction,dV:ArrayLike<number>):number{const a=reconstruct(h,g,dV);let torque=0;for(let c=0;c<h.cellCount;c++){const r=center(h,c),b=basis(r),o=c*3,ae=a[o]!*b.east[0]+a[o+1]!*b.east[1]+a[o+2]!*b.east[2],area=h.cellAreaUnit[c]!*EARTH.radius*EARTH.radius,lever=EARTH.radius*Math.sqrt(Math.max(0,1-r[2]*r[2]));torque+=area*lever*ae;}return torque;}
function leverMass(h:CubedSphereGrid):number{let m=0;for(let c=0;c<h.cellCount;c++){const r=center(h,c),area=h.cellAreaUnit[c]!*EARTH.radius*EARTH.radius,lever=EARTH.radius*Math.sqrt(Math.max(0,1-r[2]*r[2]));m+=area*lever;}return m;}
interface Metrics{exactPair:number;hodgePair:number;planetExact:number;planetH:number;cor:number;fluxRel:number;sym:number;}
function evaluate(h:CubedSphereGrid):Metrics{const V=analyticV(h),dV=analyticDV(h),Uexact=exactFaceU(h),H=buildNonorthogonalHodgeStencil(h),Uh=applyNonorthogonalHodge(H,V),rec=buildDualReconstruction(h),p0=planetaryMassTorque(h,Uexact),ph=planetaryMassTorque(h,Uh),c=relativeCoriolisTorque(h,rec,dV),scale=86400/leverMass(h);let e2=0,r2=0;for(let e=0;e<h.edgeCount;e++){const d=Uh[e]!-Uexact[e]!;e2+=d*d;r2+=Uexact[e]!*Uexact[e]!;}return{exactPair:(p0+c)*scale,hodgePair:(ph+c)*scale,planetExact:p0*scale,planetH:ph*scale,cor:c*scale,fluxRel:Math.sqrt(e2/Math.max(r2,1e-60)),sym:hodgeSymmetryDefect(H)};}
function run(n:number){return{n,raw:evaluate(buildCubedSphere(n)),mod:evaluate(buildModifiedCubedSphere(n))};}
try{const rows=[4,8,16,32].map(run),ratio=(a:number,b:number)=>Math.abs(a)/Math.max(Math.abs(b),1e-30);console.log('Stage4 primal-dual AAM prototype; analytic V and Coriolis line integrals, continuity U=HV');console.log('All torque columns equivalent m/s/day; exactPair uses exact face U, hodgePair uses H(V).');console.log('N\traw exactPair\traw H pair\tmod exactPair\tmod H pair\traw HfluxL2\tmod HfluxL2\tmod planetH\tmod Cor\tHsym');for(const r of rows)console.log(`${r.n}\t${r.raw.exactPair.toExponential(7)}\t${r.raw.hodgePair.toExponential(7)}\t${r.mod.exactPair.toExponential(7)}\t${r.mod.hodgePair.toExponential(7)}\t${r.raw.fluxRel.toExponential(6)}\t${r.mod.fluxRel.toExponential(6)}\t${r.mod.planetH.toExponential(7)}\t${r.mod.cor.toExponential(7)}\t${r.mod.sym.toExponential(2)}`);console.log(`modified H-pair refine=${ratio(rows[1]!.mod.hodgePair,rows[2]!.mod.hodgePair).toFixed(3)},${ratio(rows[2]!.mod.hodgePair,rows[3]!.mod.hodgePair).toFixed(3)} exact-pair=${ratio(rows[1]!.mod.exactPair,rows[2]!.mod.exactPair).toFixed(3)},${ratio(rows[2]!.mod.exactPair,rows[3]!.mod.exactPair).toFixed(3)}`);if(rows.some(r=>![r.raw.exactPair,r.raw.hodgePair,r.mod.exactPair,r.mod.hodgePair,r.raw.fluxRel,r.mod.fluxRel,r.mod.sym].every(Number.isFinite)))throw new Error('non-finite primal-dual AAM result');if(rows.some(r=>r.mod.sym>5e-13))throw new Error('modified H lost symmetry');}catch(e){console.error('FAIL Stage4 primal-dual AAM prototype');console.error(e);process.exitCode=1;}
