import { EARTH } from '../core/constants.js';
import { Vec3, cross3, dot3, normalize3, scale3, sub3 } from '../core/math.js';
import { CubedSphereGrid } from '../grid/cubedSphere.js';
import { DryState, edge3DIndex } from '../solver/state.js';
export interface RotationGeometry{east:Float64Array;north:Float64Array;radial:Float64Array;reconstruction:Float64Array}
function center(h:CubedSphereGrid,c:number):Vec3{return[h.cellCenters[c*3]!,h.cellCenters[c*3+1]!,h.cellCenters[c*3+2]!]}
function basisAt(r:Vec3):{east:Vec3;north:Vec3}{let e:Vec3;const xy=Math.hypot(r[0],r[1]);if(xy>1e-14)e=[-r[1]/xy,r[0]/xy,0];else e=[0,1,0];return{east:e,north:normalize3(cross3(r,e))}}
export function buildRotationGeometry(h:CubedSphereGrid):RotationGeometry{const east=new Float64Array(h.cellCount*3),north=new Float64Array(h.cellCount*3),radial=h.cellCenters.slice(),reconstruction=new Float64Array(h.cellCount*8);for(let c=0;c<h.cellCount;c++){const b=basisAt(center(h,c));east.set(b.east,c*3);north.set(b.north,c*3);let aa=0,ab=0,bb=0;const comps:[number,number][]=[];for(let s=0;s<4;s++){const e=h.edges[h.cellEdges[c*4+s]!]!,a=dot3(e.normal,b.east),q=dot3(e.normal,b.north);comps.push([a,q]);aa+=a*a;ab+=a*q;bb+=q*q}const det=aa*bb-ab*ab;if(Math.abs(det)<1e-14)throw new Error(`singular edge reconstruction at cell ${c}`);const i00=bb/det,i01=-ab/det,i11=aa/det;for(let s=0;s<4;s++){const[a,q]=comps[s]!;reconstruction[(c*4+s)*2]=i00*a+i01*q;reconstruction[(c*4+s)*2+1]=i01*a+i11*q}}return{east,north,radial,reconstruction}}
function vec(a:Float64Array,c:number):Vec3{return[a[c*3]!,a[c*3+1]!,a[c*3+2]!]}
export function reconstructCellHorizontalWind(h:CubedSphereGrid,g:RotationGeometry,s:DryState,k:number,out?:Float64Array):Float64Array{const dst=out??new Float64Array(h.cellCount*3),nz=s.uEdge.length/h.edgeCount;for(let c=0;c<h.cellCount;c++){let ue=0,vn=0;for(let slot=0;slot<4;slot++){const eid=h.cellEdges[c*4+slot]!,u=s.uEdge[edge3DIndex(eid,k,nz)]!;ue+=g.reconstruction[(c*4+slot)*2]!*u;vn+=g.reconstruction[(c*4+slot)*2+1]!*u}const e=vec(g.east,c),n=vec(g.north,c);dst[c*3]=ue*e[0]+vn*n[0];dst[c*3+1]=ue*e[1]+vn*n[1];dst[c*3+2]=ue*e[2]+vn*n[2]}return dst}
export function projectCellWindToEdges(h:CubedSphereGrid,s:DryState,k:number,cellWind:Float64Array):void{const nz=s.uEdge.length/h.edgeCount;for(let eid=0;eid<h.edgeCount;eid++){const e=h.edges[eid]!,l=e.leftCell,r=e.rightCell,avg:Vec3=[.5*(cellWind[l*3]!+cellWind[r*3]!),.5*(cellWind[l*3+1]!+cellWind[r*3+1]!),.5*(cellWind[l*3+2]!+cellWind[r*3+2]!)];s.uEdge[edge3DIndex(eid,k,nz)]=dot3(avg,e.normal)}}
export function addCellWindDeltaToEdges(h:CubedSphereGrid,s:DryState,k:number,delta:Float64Array):void{const nz=s.uEdge.length/h.edgeCount;for(let eid=0;eid<h.edgeCount;eid++){const e=h.edges[eid]!,l=e.leftCell,r=e.rightCell,avg:Vec3=[.5*(delta[l*3]!+delta[r*3]!),.5*(delta[l*3+1]!+delta[r*3+1]!),.5*(delta[l*3+2]!+delta[r*3+2]!)],q=edge3DIndex(eid,k,nz);s.uEdge[q]=s.uEdge[q]!+dot3(avg,e.normal)}}
export function rotateLocalCoriolis(ue:number,vn:number,f:number,dt:number):readonly[number,number]{const a=f*dt,co=Math.cos(a),si=Math.sin(a);return[ue*co+vn*si,vn*co-ue*si]}
export function applyTraditionalCoriolis(h:CubedSphereGrid,g:RotationGeometry,s:DryState,dt:number,omega=EARTH.omega):void{const nz=s.uEdge.length/h.edgeCount;for(let k=0;k<nz;k++){const wind=reconstructCellHorizontalWind(h,g,s,k),delta=new Float64Array(h.cellCount*3);for(let c=0;c<h.cellCount;c++){const e=vec(g.east,c),n=vec(g.north,c),r=vec(g.radial,c),w:Vec3=[wind[c*3]!,wind[c*3+1]!,wind[c*3+2]!],ue=dot3(w,e),vn=dot3(w,n),[ue2,vn2]=rotateLocalCoriolis(ue,vn,2*omega*r[2],dt);delta[c*3]=(ue2-ue)*e[0]+(vn2-vn)*n[0];delta[c*3+1]=(ue2-ue)*e[1]+(vn2-vn)*n[1];delta[c*3+2]=(ue2-ue)*e[2]+(vn2-vn)*n[2]}addCellWindDeltaToEdges(h,s,k,delta)}}
export function setAnalyticCellWind(h:CubedSphereGrid,g:RotationGeometry,s:DryState,fn:(r:Vec3,east:Vec3,north:Vec3,k:number)=>Vec3):void{const nz=s.uEdge.length/h.edgeCount;for(let k=0;k<nz;k++){const cw=new Float64Array(h.cellCount*3);for(let c=0;c<h.cellCount;c++)cw.set(fn(vec(g.radial,c),vec(g.east,c),vec(g.north,c),k),c*3);projectCellWindToEdges(h,s,k,cw)}}
export function tangent(v:Vec3,r:Vec3):Vec3{return sub3(v,scale3(r,dot3(v,r)))}
