// Model configurations. Every run is built from one of these presets.

import { DAY, DRY_AIR, EARTH } from '../core/constants.js';
import { Dycore } from './dycore.js';
import { HeldSuarezForcing, heldSuarezTeq } from './heldSuarez.js';
import { uniformSigmaHalf } from './vertical.js';
import { rng } from '../core/random.js';
import { GrayAquaplanet, GrayPhysics, GrayPhysicsConfig } from './moist/aquaplanet.js';
import { qsat } from './moist/thermo.js';

export interface HeldSuarezConfig {
  trunc: number;   // spectral truncation (21, 42, 63, 85 ...)
  levels: number;  // sigma levels
  dt: number;      // s
  seed: number;
}

export const HS_PRESETS: Record<string, HeldSuarezConfig> = {
  T21L20: { trunc: 21, levels: 20, dt: 2400, seed: 1 },
  T42L20: { trunc: 42, levels: 20, dt: 1200, seed: 1 },
  T63L20: { trunc: 63, levels: 20, dt: 900, seed: 1 },
};

/**
 * Held–Suarez dry dynamical-core climate. Starts from rest with a horizontally uniform
 * temperature profile (the global-mean radiative-equilibrium profile) plus 0.1 K grid-point
 * noise, so every circulation feature must be generated by the dynamics.
 */
export function createHeldSuarez(cfg: HeldSuarezConfig): Dycore {
  const hyperdiffTau = cfg.trunc <= 21 ? 0.25 * DAY : 0.1 * DAY;
  const model = new Dycore({
    trunc: cfg.trunc,
    sigmaHalf: uniformSigmaHalf(cfg.levels),
    dt: cfg.dt,
    planet: EARTH,
    air: DRY_AIR,
    tRef: 300,
    hyperdiffTau,
    physics: new HeldSuarezForcing(DRY_AIR),
  });
  const tr = model.tr, ng = tr.gridSize, K = model.K;
  const T = new Float64Array(ng * K), ps = new Float64Array(ng).fill(DRY_AIR.pRef);
  const r = rng(cfg.seed);
  for (let k = 0; k < K; k++) {
    const p = model.lev.sigma[k]! * DRY_AIR.pRef;
    // global mean of Teq at this pressure (area weighted by the Gaussian weights)
    let tm = 0;
    for (let j = 0; j < tr.nlat; j++) tm += tr.weight[j]! * heldSuarezTeq(tr.mu[j]!, p, DRY_AIR);
    tm /= 2;
    for (let q = 0; q < ng; q++) T[k * ng + q] = tm + 0.1 * (r() - 0.5);
  }
  model.setFromGrid(T, ps);
  return model;
}

// ---------------------------------------------------------------------------
// Moist gray-radiation aquaplanet (Frierson et al. 2006 / Isca "frierson" test case)

/** Frierson (2006) 25-level sigma half levels (top -> bottom). */
export const FRIERSON_SIGMA_HALF = Float64Array.from([
  0.000000, 0.0117665, 0.0196679, 0.0315244, 0.0485411, 0.0719344, 0.1027829, 0.1418581, 0.1894648,
  0.2453219, 0.3085103, 0.3775033, 0.4502789, 0.5244989, 0.5977253, 0.6676441, 0.7322627, 0.7900587,
  0.8400683, 0.8819111, 0.9157609, 0.9422770, 0.9625127, 0.9778177, 0.9897489, 1.0000000,
]);

export interface AquaplanetConfig { trunc: number; dt: number; seed: number }

export const AQUA_PRESETS: Record<string, AquaplanetConfig> = {
  AQUA_T21: { trunc: 21, dt: 1200, seed: 2 },
  AQUA_T42: { trunc: 42, dt: 720, seed: 2 },
  AQUA_T85: { trunc: 85, dt: 600, seed: 2 },
};

export function createAquaplanet(cfg: AquaplanetConfig): { model: Dycore; physics: GrayAquaplanet } {
  const model = new Dycore({
    trunc: cfg.trunc, sigmaHalf: FRIERSON_SIGMA_HALF, dt: cfg.dt, planet: EARTH, air: DRY_AIR,
    tRef: 300, hyperdiffTau: cfg.trunc <= 21 ? 0.25 * DAY : 0.1 * DAY, robert: 0.03, moist: true, massFixer: true,
  });
  const tr = model.tr, ng = tr.gridSize, K = model.K;
  const physics = new GrayAquaplanet(EARTH, DRY_AIR, tr.nlat, tr.nlon, K, tr.lat);
  model.columnPhysics = physics;
  const T = new Float64Array(ng * K), q = new Float64Array(ng * K), ps = new Float64Array(ng).fill(DRY_AIR.pRef);
  const r = rng(cfg.seed);
  const expo = DRY_AIR.rd * 0.0065 / EARTH.gravity;
  for (let k = 0; k < K; k++) {
    const sig = model.lev.sigma[k]!;
    for (let j = 0; j < tr.nlat; j++) {
      const c2 = 1 - tr.mu[j]! ** 2;
      const ts = 270 + 35 * c2;
      for (let i = 0; i < tr.nlon; i++) {
        const idx = k * ng + j * tr.nlon + i;
        T[idx] = Math.max(200, (ts - 5) * Math.pow(sig, expo)) + 0.1 * (r() - 0.5);
        q[idx] = sig > 0.5 ? 0.5 * qsat(T[idx]!, sig * DRY_AIR.pRef) : 2e-6;
      }
    }
  }
  model.setFromGrid(T, ps);
  model.setMoisture(q);
  return { model, physics };
}

// ---------------------------------------------------------------------------
// Earth: real land–sea mask and orography, seasonal insolation, gray radiation with
// water-vapour-dependent longwave optical depth (Byrne & O'Gorman 2013), slab ocean with
// prescribed ocean heat transport, bucket land hydrology, simple sea-ice albedo.

/** Surface dataset on a regular or Gaussian lat-lon grid (lat north -> south, lon from 0 east). */
export interface EarthData { nlat: number; nlon: number; lat: number[]; lon: number[]; zsurf_m: number[]; land: number[] }

export interface EarthConfig { trunc: number; dt: number; seed: number }
export const EARTH_PRESETS: Record<string, EarthConfig> = {
  EARTH_T21: { trunc: 21, dt: 1200, seed: 3 },
  EARTH_T42: { trunc: 42, dt: 720, seed: 3 },
  EARTH_T85: { trunc: 85, dt: 600, seed: 3 },
};

export const EARTH_PHYSICS: Partial<GrayPhysicsConfig> = {
  radiation: 'byrne', seasonal: true, obliquityDeg: 23.44, yearLength: 365.25 * DAY,
  albedo: 0.31, albedoLand: 0.31, albedoIce: 0.6,
  mixedLayerDepth: 20, landHeatCapacity: 2e6, roughness: 3.21e-5, roughnessLand: 0.05, bucketMax: 0.15,
  qflux: true, qfluxAmp: 30, qfluxWidthDeg: 16,
};

/** Bilinear interpolation of a lat-lon dataset to model points (lat, lon in radians). */
export function sampleEarth(d: EarthData, field: number[], lat: number, lon: number): number {
  const la = lat * 180 / Math.PI;
  let lo = lon * 180 / Math.PI;
  lo = ((lo % 360) + 360) % 360;
  const L = d.lat;
  let j = 0;
  while (j < d.nlat - 2 && L[j + 1]! > la) j++;
  const wy = Math.max(0, Math.min(1, (L[j]! - la) / (L[j]! - L[j + 1]!)));
  const dx = 360 / d.nlon, x = (lo - d.lon[0]!) / dx;
  const i0 = ((Math.floor(x) % d.nlon) + d.nlon) % d.nlon, i1 = (i0 + 1) % d.nlon, wx = x - Math.floor(x);
  const at = (jj: number): number => field[jj * d.nlon + i0]! * (1 - wx) + field[jj * d.nlon + i1]! * wx;
  return at(j) * (1 - wy) + at(j + 1) * wy;
}

export function createEarth(cfg: EarthConfig, data: EarthData, physicsOverrides: Partial<GrayPhysicsConfig> = {}): { model: Dycore; physics: GrayPhysics } {
  const model = new Dycore({
    trunc: cfg.trunc, sigmaHalf: FRIERSON_SIGMA_HALF, dt: cfg.dt, planet: EARTH, air: DRY_AIR,
    tRef: 300, hyperdiffTau: cfg.trunc <= 21 ? 0.25 * DAY : 0.1 * DAY, robert: 0.03, moist: true, massFixer: true,
  });
  const tr = model.tr, ng = tr.gridSize, K = model.K, nlon = tr.nlon;
  const land = new Uint8Array(ng), zs = new Float64Array(ng), phis = new Float64Array(ng);
  for (let j = 0; j < tr.nlat; j++) for (let i = 0; i < nlon; i++) {
    const p = j * nlon + i;
    land[p] = sampleEarth(data, data.land, tr.lat[j]!, tr.lon[i]!) >= 0.5 ? 1 : 0;
    zs[p] = Math.max(0, sampleEarth(data, data.zsurf_m, tr.lat[j]!, tr.lon[i]!));
    phis[p] = EARTH.gravity * zs[p]!;
  }
  model.setSurfaceGeopotential(phis, 0.1);
  model.surfaceGeopotentialGrid(phis);
  for (let p = 0; p < ng; p++) zs[p] = Math.max(0, phis[p]! / EARTH.gravity);
  const physics = new GrayPhysics(EARTH, DRY_AIR, tr.nlat, nlon, K, tr.lat, { ...EARTH_PHYSICS, ...physicsOverrides }, { land, zsurf: zs });
  model.columnPhysics = physics;
  const T = new Float64Array(ng * K), q = new Float64Array(ng * K), ps = new Float64Array(ng);
  const r = rng(cfg.seed);
  const expo = DRY_AIR.rd * 0.0065 / EARTH.gravity;
  for (let j = 0; j < tr.nlat; j++) for (let i = 0; i < nlon; i++) {
    const p = j * nlon + i;
    const tsfc = physics.f.sst[p]!;
    ps[p] = DRY_AIR.pRef * Math.exp(-phis[p]! / (DRY_AIR.rd * 280));
    for (let k = 0; k < K; k++) {
      const sig = model.lev.sigma[k]!, idx = k * ng + p;
      T[idx] = Math.max(200, (tsfc - 5) * Math.pow(sig, expo)) + 0.1 * (r() - 0.5);
      q[idx] = sig > 0.5 ? 0.5 * qsat(T[idx]!, sig * ps[p]!) : 2e-6;
    }
  }
  model.setFromGrid(T, ps);
  model.setMoisture(q);
  return { model, physics };
}
