// Model configurations. Every run is built from one of these presets.

import { DAY, DRY_AIR, EARTH } from '../core/constants.js';
import { Dycore } from './dycore.js';
import { HeldSuarezForcing, heldSuarezTeq } from './heldSuarez.js';
import { uniformSigmaHalf } from './vertical.js';
import { rng } from '../core/random.js';

export interface HeldSuarezConfig {
  trunc: number;   // spectral truncation (21, 42, 63, 85 ...)
  levels: number;  // sigma levels
  dt: number;      // s
  seed: number;
}

export const HS_PRESETS: Record<string, HeldSuarezConfig> = {
  T21L20: { trunc: 21, levels: 20, dt: 2400, seed: 1 },
  T42L20: { trunc: 42, levels: 20, dt: 1200, seed: 1 },
  T63L20: { trunc: 63, levels: 20, dt: 900, seed: 1 },
};

/**
 * Held–Suarez dry dynamical-core climate. Starts from rest with a horizontally uniform
 * temperature profile (the global-mean radiative-equilibrium profile) plus 0.1 K grid-point
 * noise, so every circulation feature must be generated by the dynamics.
 */
export function createHeldSuarez(cfg: HeldSuarezConfig): Dycore {
  const hyperdiffTau = cfg.trunc <= 21 ? 0.25 * DAY : 0.1 * DAY;
  const model = new Dycore({
    trunc: cfg.trunc,
    sigmaHalf: uniformSigmaHalf(cfg.levels),
    dt: cfg.dt,
    planet: EARTH,
    air: DRY_AIR,
    tRef: 300,
    hyperdiffTau,
    physics: new HeldSuarezForcing(DRY_AIR),
  });
  const tr = model.tr, ng = tr.gridSize, K = model.K;
  const T = new Float64Array(ng * K), ps = new Float64Array(ng).fill(DRY_AIR.pRef);
  const r = rng(cfg.seed);
  for (let k = 0; k < K; k++) {
    const p = model.lev.sigma[k]! * DRY_AIR.pRef;
    // global mean of Teq at this pressure (area weighted by the Gaussian weights)
    let tm = 0;
    for (let j = 0; j < tr.nlat; j++) tm += tr.weight[j]! * heldSuarezTeq(tr.mu[j]!, p, DRY_AIR);
    tm /= 2;
    for (let q = 0; q < ng; q++) T[k * ng + q] = tm + 0.1 * (r() - 0.5);
  }
  model.setFromGrid(T, ps);
  return model;
}
