import { buildCubedSphere } from './grid/cubedSphere.js';
import { buildStretchedVerticalGrid } from './grid/vertical.js';
import { acousticDivergenceCoefficientForDt } from './physics/acousticDivergenceDamping.js';
import { buildHeldSuarezReference } from './physics/heldSuarez.js';
import { createHydrostaticState } from './solver/state.js';
import { diagnoseState } from './solver/diagnostics.js';
import { STAGE4_HEVI_OFFCENTERING } from './solver/stage4Config.js';
import { GpuStage4Integrator } from './gpu/stage4IntegratorGpu.js';
import { ClimateDaySample, runHeldSuarezGpuClimate, runStage4GpuAgreement, Stage4AgreementSample } from './validation/stage4Gpu.js';
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;const logEl=$<HTMLDivElement>('log'),log=(x:string)=>{logEl.textContent=`${x}\n${logEl.textContent||''}`.slice(0,20000)},agreeBtn=$<HTMLButtonElement>('agree'),climateBtn=$<HTMLButtonElement>('climate');let smoke=false;
function lock(v:boolean){agreeBtn.disabled=v||!smoke;climateBtn.disabled=v||!smoke}
function agreementSample(s:Stage4AgreementSample){$('agreeStep').textContent=String(s.step);$('agreeMass').textContent=s.massDrift.toExponential(3);$('agreeRho').textContent=s.rhoL2.toExponential(3);$('agreeTheta').textContent=s.rhoThetaL2.toExponential(3);$('agreeU').textContent=`${s.uMaxDiff.toExponential(3)} m/s`;$('agreeW').textContent=`${s.wMaxDiff.toExponential(3)} m/s`;log(`Stage 4 GPU/CPU checkpoint ${s.step}: mass=${s.massDrift.toExponential(3)}, rhoL2=${s.rhoL2.toExponential(3)}, rhoThetaL2=${s.rhoThetaL2.toExponential(3)}, du=${s.uMaxDiff.toExponential(3)}, dw=${s.wMaxDiff.toExponential(3)}.`)}
function climateSample(s:ClimateDaySample){$('climateDay').textContent=`${s.day.toFixed(s.day%1===0?0:2)} / 30`;$('climateMass').textContent=s.massDrift.toExponential(3);$('climateJet').textContent=`${s.jet.toFixed(3)} m/s`;$('climateTrade').textContent=`${s.trade.toFixed(3)} m/s`;$('climatePsi').textContent=s.psi.toExponential(3);$('climateW').textContent=`${s.maxW.toExponential(3)} m/s`;log(`Held–Suarez day ${s.day.toFixed(2)}: mass=${s.massDrift.toExponential(3)}, jet=${s.jet.toFixed(3)}, trade=${s.trade.toFixed(3)}, psi=${s.psi.toExponential(3)}, max|w|=${s.maxW.toExponential(3)}.`)}
agreeBtn.onclick=()=>void(async()=>{lock(true);$('agreeStatus').textContent='執行中 / Running';$('agreeStatus').className='';try{const r=await runStage4GpuAgreement(agreementSample);$('agreeElapsed').textContent=`${(r.elapsedMs/1000).toFixed(2)} s`;$('agreeStatus').textContent=r.passed?'通過 / PASS':'失敗 / FAIL';$('agreeStatus').className=r.passed?'ok':'bad';log(r.passed?'Stage 4 GPU/CPU 一致性 gate 通過。 / Stage 4 GPU/CPU agreement gate PASS.':`Stage 4 GPU/CPU 一致性 gate 失敗 / FAIL:\n${r.failures.join('\n')}`)}catch(e){$('agreeStatus').textContent='錯誤 / ERROR';$('agreeStatus').className='bad';log(`Stage 4 agreement error: ${String(e)}`)}finally{lock(false)}})();
climateBtn.onclick=()=>void(async()=>{lock(true);$('climateStatus').textContent='執行中 / Running';$('climateStatus').className='';log(`30 日 gate 每 timestep 套用時間尺度化 divergence damping + top sponge；dt=10 s 時 γ=${acousticDivergenceCoefficientForDt(10).toFixed(5)}。 / 30-day gate uses per-timestep time-normalized divergence damping + top sponge; at dt=10 s, gamma=${acousticDivergenceCoefficientForDt(10).toFixed(5)}.`);try{const r=await runHeldSuarezGpuClimate(30,climateSample);$('climateElapsed').textContent=`${(r.elapsedMs/1000).toFixed(2)} s`;$('climateStatus').textContent=r.passed?'通過 / PASS':'失敗 / FAIL';$('climateStatus').className=r.passed?'ok':'bad';log(r.passed?'30 日 Held–Suarez 旋轉乾大氣發展 gate 通過。 / 30-day Held–Suarez rotating dry-atmosphere development gate PASS.':`30-day Held–Suarez gate FAIL:\n${r.failures.join('\n')}`)}catch(e){$('climateStatus').textContent='錯誤 / ERROR';$('climateStatus').className='bad';log(`Held–Suarez climate error: ${String(e)}`)}finally{lock(false)}})();
(async()=>{try{const h=buildCubedSphere(4),v=buildStretchedVerticalGrid(12,30000,1.4),ref=buildHeldSuarezReference(v),gpu=await GpuStage4Integrator.create(h,v,ref,createHydrostaticState(h,v,ref));gpu.step(1,false);const s=await gpu.downloadState(1),d=diagnoseState(h,v,s);if(d.nan||d.minRho<=0||d.minP<=0)throw new Error('invalid Stage 4 smoke state');gpu.destroy();smoke=true;$('gpuStatus').textContent=`旋轉 GPU + HEVI ε=${STAGE4_HEVI_OFFCENTERING.toFixed(2)} + 時間尺度化每步穩定化 smoke 通過 / Rotating GPU + HEVI off-centering + time-normalized per-step stabilizers smoke PASS`;$('gpuStatus').className='ok';log(`Stage 4 WebGPU rotating core with HEVI epsilon=${STAGE4_HEVI_OFFCENTERING.toFixed(2)} and time-normalized per-timestep divergence/top-sponge stabilizers compiled and executed; smoke max|w|=${d.maxAbsW.toExponential(3)} m/s.`);lock(false)}catch(e){smoke=false;$('gpuStatus').textContent='失敗 / FAIL';$('gpuStatus').className='bad';agreeBtn.disabled=true;climateBtn.disabled=true;log(`Stage 4 WebGPU smoke failed: ${String(e)}`)}})();
